/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.Xbox;
import model.bean.game;
import model.dao.gameDAO;
import model.bean.Ps5;

/**
 *
 * @author luizc
 */
public class frmGame extends javax.swing.JFrame {

    /**
     * Creates new form frmGame
     */
    public frmGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdgame = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeDoVideoGame = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNomeDoJogo = new javax.swing.JTextField();
        Processador = new javax.swing.JLabel();
        txtMemoria = new javax.swing.JTextField();
        cor1 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        PlacaVideo = new javax.swing.JLabel();
        txtProcessador = new javax.swing.JTextField();
        PlacaVideo1 = new javax.swing.JLabel();
        txtPlacaV = new javax.swing.JTextField();
        PlacaVideo2 = new javax.swing.JLabel();
        txtQtdControle = new javax.swing.JTextField();
        PlacaVideo3 = new javax.swing.JLabel();
        txtR4k = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID Game");

        txtIdgame.setEditable(false);
        txtIdgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdgameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Video Game");

        txtNomeDoVideoGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoVideoGameActionPerformed(evt);
            }
        });

        btnInserir.setBackground(new java.awt.Color(0, 0, 0));
        btnInserir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInserir.setForeground(new java.awt.Color(51, 204, 0));
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        btnPesquisar.setForeground(new java.awt.Color(51, 51, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(0, 0, 0));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 0));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(0, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(204, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome Do Jogo");

        txtNomeDoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoJogoActionPerformed(evt);
            }
        });

        Processador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Processador.setText("Processador");

        txtMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemoriaActionPerformed(evt);
            }
        });

        cor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cor1.setText("Cor");

        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        PlacaVideo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaVideo.setText("Placa de Video");

        txtProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcessadorActionPerformed(evt);
            }
        });

        PlacaVideo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaVideo1.setText("Quantidade de Controle");

        txtPlacaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaVActionPerformed(evt);
            }
        });

        PlacaVideo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaVideo2.setText("Memoria");

        txtQtdControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdControleActionPerformed(evt);
            }
        });

        PlacaVideo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PlacaVideo3.setText("Roda Jogos 4K");

        txtR4k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR4kActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("Cadastro de Video Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomeDoVideoGame, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cor1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Processador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlacaVideo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPlacaV, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlacaVideo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQtdControle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlacaVideo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtR4k, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlacaVideo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                                .addComponent(txtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomeDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                                .addComponent(txtIdgame, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addGap(29, 29, 29)
                                .addComponent(btnExcluir)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdgame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeDoVideoGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeDoJogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cor1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Processador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProcessador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlacaVideo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPlacaV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlacaVideo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMemoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlacaVideo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQtdControle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlacaVideo3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtR4k, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdgameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdgameActionPerformed

    private void txtNomeDoVideoGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoVideoGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoVideoGameActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        gameDAO dao = new gameDAO();
        game g = new game();
        Xbox x = new Xbox();
        Ps5 p = new Ps5();

        g.setNomeDoVideoGame(txtNomeDoVideoGame.getText());
        g.setNomeDoJogo(txtNomeDoJogo.getText());
        x.setCor(txtCor.getText());
        x.setProcessador(txtProcessador.getText());
        x.setPlacaVideo(txtPlacaV.getText());
        p.setMemoria(txtMemoria.getText());
        p.setQtdControle(txtQtdControle.getText());
        p.setRoda4k(txtR4k.getText());

        dao.create(g, x, p);

        txtIdgame.setText("");
        txtNomeDoVideoGame.setText("");
        txtNomeDoJogo.setText("");
        txtCor.setText("");
        txtProcessador.setText("");
        txtPlacaV.setText("");
        txtMemoria.setText("");
        txtQtdControle.setText("");
        txtR4k.setText("");

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (txtNomeDoJogo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Permitido somente efetuar busca pelo nome do jogo");

        } else {
            game g = new game();
            gameDAO dao = new gameDAO();

            g = dao.read(txtNomeDoJogo.getText());

            if (g.getNomeDoJogo() != null) {
                txtIdgame.setText(String.valueOf(g.getIdVideoGame()));
                txtNomeDoVideoGame.setText(g.getNomeDoVideoGame());
                txtNomeDoJogo.setText(g.getNomeDoJogo());
                txtCor.setText(g.getXbox().getCor());
                txtProcessador.setText(g.getXbox().getProcessador());
                txtPlacaV.setText(g.getXbox().getPlacaVideo());
                txtMemoria.setText(g.getPs5().getMemoria());
                txtQtdControle.setText(g.getPs5().getQtdControle());
                txtR4k.setText(g.getPs5().getRoda4k());

            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        game g = new game();
        gameDAO dao = new gameDAO();
        Xbox x = new Xbox();
        Ps5 p = new Ps5();

        g.setIdVideoGame(Integer.parseInt(txtIdgame.getText()));
        g.setNomeDoVideoGame(txtNomeDoVideoGame.getText());
        g.setNomeDoJogo(txtNomeDoJogo.getText());
        x.setCor(txtCor.getText());
        x.setProcessador(txtProcessador.getText());
        x.setPlacaVideo(txtPlacaV.getText());
        p.setMemoria(txtMemoria.getText());
        p.setQtdControle(txtQtdControle.getText());
        p.setRoda4k(txtR4k.getText());

        dao.update(g, x, p);

        txtIdgame.setText("");
        txtNomeDoVideoGame.setText("");
        txtNomeDoJogo.setText("");
        txtCor.setText("");
        txtProcessador.setText("");
        txtPlacaV.setText("");
        txtMemoria.setText("");
        txtQtdControle.setText("");
        txtR4k.setText("");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        game g = new game();
        gameDAO dao = new gameDAO();
        
        g.setNomeDoJogo(txtNomeDoJogo.getText());
        dao.delete(g);

        txtIdgame.setText("");
        txtNomeDoVideoGame.setText("");
        txtNomeDoJogo.setText("");
        txtCor.setText("");
        txtProcessador.setText("");
        txtPlacaV.setText("");
        txtMemoria.setText("");
        txtQtdControle.setText("");
        txtR4k.setText("");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeDoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoJogoActionPerformed

    private void txtMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemoriaActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcessadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcessadorActionPerformed

    private void txtPlacaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaVActionPerformed

    private void txtQtdControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdControleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdControleActionPerformed

    private void txtR4kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR4kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR4kActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlacaVideo;
    private javax.swing.JLabel PlacaVideo1;
    private javax.swing.JLabel PlacaVideo2;
    private javax.swing.JLabel PlacaVideo3;
    private javax.swing.JLabel Processador;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel cor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtIdgame;
    private javax.swing.JTextField txtMemoria;
    private javax.swing.JTextField txtNomeDoJogo;
    private javax.swing.JTextField txtNomeDoVideoGame;
    private javax.swing.JTextField txtPlacaV;
    private javax.swing.JTextField txtProcessador;
    private javax.swing.JTextField txtQtdControle;
    private javax.swing.JTextField txtR4k;
    // End of variables declaration//GEN-END:variables
}
